### ISSUE TITLE
分辨率配置1728x1080

### ISSUE THREAD

**Issue by RealSlakey** [CalvinXu17/PUBG-Logitech#1]
想新增分辨率配置1728x1080，不知道在resolution里直接新增分辨率json后修改坐标能否读取的到

**Comment by KingShing** [comment]
app内参数设置，没有持久化（数据库，或者文件 落地更好），每次打开软件都需要重新改，比如 click hold模式等

**Comment by Jinkouyanmai** [comment]
> 
那个群你能加进入吗
