### ISSUE TITLE
导入lua总有问题

### ISSUE THREAD

**Issue by Genius2333** [CalvinXu17/PUBG-Logitech#10]
![未命名1714460647](https://github.com/CalvinXu17/PUBG-Logitech/assets/139752467/fa967220-1863-4f43-8e22-7f5cd273bbd6)
总会报错

**Comment by CalvinXu17** [comment]
发一下C://Users/23723/AppData/Local/Temp/weapon.lua文件

**Comment by Genius2333** [comment]
[weapon.lua.txt](https://github.com/CalvinXu17/PUBG-Logitech/files/15159715/weapon.lua.txt)
我改了下后缀

**Comment by CalvinXu17** [comment]
```
ballistic={
{1,43},**wa**
{2,43},
{3,36},
{4,30},
```
m762的弹道数据你多加了wa

**Comment by Genius2333** [comment]
> ```
> ballistic={
> {1,43},**wa**
> {2,43},
> {3,36},
> {4,30},
> ```
> 
> m762的弹道数据你多加了wa

等下我看看去, 可能误触了

**Comment by Genius2333** [comment]
> > ```
> > ballistic={
> > {1,43},**wa**
> > {2,43},
> > {3,36},
> > {4,30},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > m762的弹道数据你多加了wa
> 
> 等下我看看去, 可能误触了

还真是误触了, 尴尬

**Comment by Genius2333** [comment]
还有个问题, 软件里匹配垂直灵敏度只能设置一位小数

**Comment by CalvinXu17** [comment]
回头我看一下
