### ISSUE TITLE
修改武器参数，不生效

### ISSUE THREAD

**Issue by zzz583974851** [CalvinXu17/PUBG-Logitech#11]
修改武器参数，点击保存，或者点击保存加应用不生效，必须关闭hub，重新打开才行，是不是有缓存bug

**Comment by mrtliasdasdas** [comment]
me too

**Comment by CalvinXu17** [comment]
> 修改武器参数，点击保存，或者点击保存加应用不生效，必须关闭hub，重新打开才行，是不是有缓存bug

这是GHUB的问题，需要重新加载脚本才能生效
