### ISSUE TITLE
没有8倍镜片，失败功能

### ISSUE THREAD

**Issue by zzz583974851** [CalvinXu17/PUBG-Logitech#12]
没有8倍镜片，失败功能

**Comment by CalvinXu17** [comment]
8倍压枪意义不大，暂不打算加上，影响6倍镜识别

**Comment by zzz583974851** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zzz583974851** [comment]
8倍压枪有意义的，对于连狙来说，目前没有8倍压枪会导致BUG，就是使用8倍会被识别成6倍的压强数据
