### ISSUE TITLE
有几点要求不知道作者能否有时间更改？

### ISSUE THREAD

**Issue by 332701232** [CalvinXu17/PUBG-Logitech#14]
1，软件界面太大了，希望小点。（因为需要看自动识别枪是否正确，有的时候会识别错误，界面太大影响游戏画面）
2，识别是否蹲下的时候，在车上没有小人识别不了，能不能当识别不出来的时候默认为站立姿态？
3，能否加上一键捡枪功能？
谢谢作者

**Comment by CalvinXu17** [comment]
1. 软件界面大小后面有空改一下
2. 目前检测不出默认蹲姿，防止识别错误的情况下用站姿会压过。个人实测发现软件少压一点好于压过头的情况
3. 暂时没有计划做一键拾取功能，软件只做核心的识别与压枪
