### ISSUE TITLE
大佬您好，dxgi初始化失败，软件启动后会自动退出

### ISSUE THREAD

**Issue by b0ssxie** [CalvinXu17/PUBG-Logitech#22]
打开软件会弹出DXGI初始化失败，但是其他功能正常。保存加载宏后enable再进游戏软件就会未响应然后直接退出
![b7b15b43e19660dab9d06d4aa85a4eac](https://github.com/user-attachments/assets/59d927b3-879a-407c-a475-aee1778718ce)

**Comment by b0ssxie** [comment]
我看了下这个报错后还是能正常识别，但是并没有压枪效果，lua也加载到ghub里了，其他软件通过ghub移动鼠标都正常

**Comment by CalvinXu17** [comment]
识别正常是因为自动调用了GDI截图，识别与压枪是分开的，识别正常但不压枪请检查GHUB脚本
